apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enterprise-tdf-configuration-redis-ha-np
  namespace: virtru
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: redis-ha
      ports:
        - port: 26379
          protocol: TCP
  podSelector:
    matchLabels:
      app: redis-ha
  policyTypes:
    - Ingress
