# Default values for audit-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/virtru-corp/audit-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.22.0-8057e1b

imagePullSecrets:
  - name: platform-pull-secret
nameOverride: ""
fullnameOverride: ""

config:
  db:
    ## @param config.db.host Postgresql DB Host
    host: "postgresql"
    ## @param config.db.user Postgresql DB Username
    user: "audit_manager"
    ## @param config.db.port Postgresql DB Port
    port: 5432
    ## @param config.db.dbName Postgresql DB Name
    dbName: "audit_database"
    ## @param config.db.sslMode Postgresql SSL Mode
    sslMode: "disable"
  secrets:
    ## @param config.secrets.dbPassword Postgresql Database password - used if `config.existingSecret` is blank
    dbPassword:


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


podAnnotations:
  proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  name: audit
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
