apiVersion: v2
name: configuration
description: A Helm chart fo OpenTDF Configuration, a service for providing configuration to applications and other services.
type: application
version: 0.3.0
appVersion: 0.3.5
kubeVersion: ">=1.24.0-0"
home: https://github.com/opentdf/backend/tree/main/charts/configuration
icon: https://avatars.githubusercontent.com/u/90051847?s=200&v=4
sources:
  - https://github.com/virtru-corp/virtru-charts/tree/feature/csp/scp/charts/configuration
keywords:
  - opentdf
  - configuration
  - PEP
maintainers:
  - name: opentdf
    url: https://opentdf.io/
dependencies:
  - name: redis-ha
    version: 4.23.0
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled
