{{- if and .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.fullname }}
  labels:
{{/*    {{- include "configuration.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name) | nindent 4 }}*/}}
    {{- with .Values.redis.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.redis.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.redis.service.servicePort }}
      targetPort: {{ .Values.redis.service.name }}
      name: {{ .Values.redis.service.name }}
  selector:
{{/*    {{- include "configuration.selectorLabels" (dict "context" . "name" .Values.redis.name) | nindent 4 }}*/}}
  {{- end }}
