fluent-bit:
  kind: DaemonSet
  image:
    repository: cr.fluentbit.io/fluent/fluent-bit
    # Overrides the image tag whose default is {{ .Chart.AppVersion }}
    tag: "2.1.4"
    pullPolicy: IfNotPresent
  podSecurityPolicy:
    create: true
    annotations: {}
  podAnnotations: {}
  config:
    service: |
      [SERVICE]
          Daemon                    Off
          Flush                     1
          Log_Level                 info
          Parsers_File              parsers.conf
          HTTP_Server               On
          HTTP_Listen               0.0.0.0
          HTTP_Port                 2020
          Health_Check              On
          storage.path              /var/log/flb-storage/
          storage.sync              normal
          storage.checksum          off
          storage.max_chunks_up     256
          storage.backlog.mem_limit 5M
          storage.metrics           on
    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name             tail
          Path             /var/log/containers/*
          multiline.parser docker,cri
          Exclude_Path     /var/log/containers/*fluent-bit*
          Tag              kube.*
          Mem_Buf_Limit    10MB
          Buffer_Chunk_Size 64k
          Buffer_Max_Size  1MB
          Skip_Long_Lines  off
          storage.type     filesystem
          db               virtru-flb.db
          db.locking       true
          db.sync          full
    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name             kubernetes
          Match            kube.*
          Kube_URL         https://kubernetes.default.svc:443
          Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
          Kube_Tag_Prefix  kube.var.log.containers.
          Merge_Log        On
          Buffer_Size      96k
          Keep_Log         Off
      [FILTER]
          Name       record_modifier
          Match      kube.*
          Remove_key stream
          Remove_key _p
      [FILTER]
          Name         rewrite_tag
          Match        kube.var.log.containers.*
          Rule         $levelname ^(AUDIT)$ audit false
          Emitter_Name audit_emitter
    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name        http
          Match       audit
          Host        audit-api.shp.svc.cluster.local
          URI         /api/v1/write
          Port        8080
          tls         off
          tls.verify  off
          Format      json
          Retry_Limit 8