{{- if and .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.fullname }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.redis.name }}
    service: {{ .Chart.Name }}-{{ .Values.redis.name }}
  {{- with .Values.redis.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.redis.service.servicePort }}
      targetPort: {{ .Values.redis.service.name }}
      name: {{ .Values.redis.service.name }}
  selector:
    app: {{ .Chart.Name }}-{{ .Values.redis.name }}
{{- end }}
