{{- if and .Values.redis.enabled -}}
{{- if and .Values.redis.storage.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.redis.storage.name }}
  namespace: {{ .Release.Namespace | quote }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
{{- end -}}
{{- end -}}
