apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.redis.storage.name }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
